### ISSUE TITLE
[Security] Workflow code-quality.yml is using vulnerable action wagoid/commitlint-github-action

### ISSUE THREAD

**Issue by igibek** [aryella-lacerda/react-native-accessibility-engine#160]
The workflow code-quality.yml is referencing action wagoid/commitlint-github-action using references v1. However this reference is missing the commit [bf83d2b35c4177779d047f464b48d9907f2c5201](https://github.com/wagoid/commitlint-github-action/commits/bf83d2b35c4177779d047f464b48d9907f2c5201) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by aryella-lacerda** [comment]
Hello, @igibek! 😁

If I'm understanding you correctly, you'd like to upgrade `wagoid/commitlint-github-action`, used in the code-quality pipeline, from v1 to v4?

It's true that the first version of the project used v1, but it was upgraded to v4 in August of 2021: https://github.com/aryella-lacerda/react-native-accessibility-engine/pull/70

Can you confirm this is what you meant?

**Comment by aryella-lacerda** [comment]
As stated above, this problem seems to have been addressed already. Closing!
