### ISSUE TITLE
Feat: support internal asynchronous updates

### ISSUE THREAD

**Issue by jsamr** [aryella-lacerda/react-native-accessibility-engine#97]
Currently, the API only supports `react-test-renderer`, which doesn't handle internal asynchronous updates (such as an Image component fetching its source and updating thereafter). This will lead to warnings such as
```
Warning: An update to XXX inside a test was not wrapped in act(...).
    
    When testing, code that causes React state updates should be wrapped into act(...):
    
    act(() => {
      /* fire events that update state */
    });
    /* assert on the output */
```

A solution is to use [`react-native-testing-library`](https://github.com/callstack/react-native-testing-library) from callstack instead. It would be nice to provide a sibling function to `check` which would render in `react-native-testing-library` `render` function and  thus support internal async updates.

```js
import { waitFor } from "react-native-testing-library";
// ...
await waitFor(expect(() => AccessibilityEngine.checkAsync(element)).not.toThrow());
```

More details in this post: https://davidwcai.medium.com/react-testing-library-and-the-not-wrapped-in-act-errors-491a5629193b#5bbc

**Comment by aryella-lacerda** [comment]
Hi there @jsamr!

You're right, this library as it stands right now doesn't consider async use cases. 🤔 It shouldn't be too difficult to provide a sibling function as you suggested, or even to yank out `react-test-renderer` and use `react-native-testing-library` instead. RNTL is built on top of `react-test-renderer`, so the migration should be painless.

The only thing that bothers me about this is that `react-native-testing-library` would then become a second peer dependency, alongside `react-test-renderer`. 🤔  

My workload's tough this week, so it might be few days before I can sit down to work on this, but I'll update this issue as I go. ✌🏼 We're happy to accept PRs too, if you're interested.
